/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTrainingModal: typeof import('./src/components/training/AddTrainingModal.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AssistantMessage: typeof import('./src/components/chat/AssistantMessage.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/chat/EmptyState.vue')['default']
    HistoryItem: typeof import('./src/components/history/HistoryItem.vue')['default']
    HistorySidebar: typeof import('./src/components/history/HistorySidebar.vue')['default']
    LoadingIndicator: typeof import('./src/components/chat/LoadingIndicator.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    PageContent: typeof import('./src/components/common/PageContent.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PlotlyChart: typeof import('./src/components/chat/PlotlyChart.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    ResultsTable: typeof import('./src/components/chat/ResultsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SQLDisplay: typeof import('./src/components/chat/SQLDisplay.vue')['default']
    StatsCards: typeof import('./src/components/common/StatsCards.vue')['default']
    TrainingDataTable: typeof import('./src/components/training/TrainingDataTable.vue')['default']
    UserMessage: typeof import('./src/components/chat/UserMessage.vue')['default']
    ViewTrainingModal: typeof import('./src/components/training/ViewTrainingModal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
