services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: detomo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv  # Don't mount venv
      - detomo-vectordb:/app/detomo_vectordb  # Persist training data
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - detomo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v0/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: detomo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - DOCKER=true
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    networks:
      - detomo-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  detomo-vectordb:
    name: detomo-vectordb-dev

networks:
  detomo-network:
    driver: bridge
